# Generated by Django 4.2.2 on 2023-07-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pixels_x1', models.IntegerField()),
                ('pixels_x2', models.IntegerField()),
                ('pixels_y1', models.IntegerField()),
                ('pixels_y2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=3)),
                ('final_hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='iffley_app.hold')),
                ('holds', models.ManyToManyField(to='iffley_app.hold')),
            ],
        ),
    ]
