# Generated by Django 4.2.2 on 2023-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='start_holds',
            field=models.ManyToManyField(related_name='starting_holds', to='iffley_app.hold'),
        ),
        migrations.AlterField(
            model_name='route',
            name='holds',
            field=models.ManyToManyField(related_name='holds', to='iffley_app.hold'),
        ),
    ]
