# Generated by Django 4.2.2 on 2023-07-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0002_route_start_holds_alter_route_holds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='final_hold',
        ),
    ]
