# Generated by Django 4.2.2 on 2023-07-02 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0003_remove_route_final_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='final_hold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='iffley_app.hold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
