# Generated by Django 4.2.2 on 2023-07-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0004_route_final_hold_alter_route_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='final_hold',
        ),
    ]
