# Generated by Django 4.2.2 on 2023-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0005_remove_route_final_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
