# Generated by Django 4.2.2 on 2023-08-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0007_route_holds_str_route_stand_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FurlongGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='grade',
        ),
        migrations.AddField(
            model_name='route',
            name='b_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='furlong_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='other_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tech_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
