# Generated by Django 4.2.2 on 2023-08-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0008_bgrade_furlonggrade_techgrade_remove_route_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='b_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_grade', to='iffley_app.bgrade'),
        ),
        migrations.AlterField(
            model_name='route',
            name='furlong_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furlong_grade', to='iffley_app.furlonggrade'),
        ),
        migrations.AlterField(
            model_name='route',
            name='other_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_grade', to='iffley_app.furlonggrade'),
        ),
        migrations.AlterField(
            model_name='route',
            name='tech_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_grade', to='iffley_app.techgrade'),
        ),
    ]
