# Generated by Django 4.2.2 on 2023-08-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0009_alter_route_b_grade_alter_route_furlong_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='other_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
