# Generated by Django 4.2.2 on 2023-08-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0010_alter_route_other_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
