# Generated by Django 4.2.2 on 2023-08-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0013_alter_route_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('long_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_all',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_ambulance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_dyno',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_finger',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_flex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_infamous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_strong',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_tall',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tag_tech',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='iffley_app.section'),
        ),
    ]
