# Generated by Django 4.2.2 on 2023-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0014_section_route_description_route_stars_route_tag_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
