# Generated by Django 4.2.2 on 2023-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0015_alter_route_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
