# Generated by Django 4.2.2 on 2023-09-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffley_app', '0017_alter_route_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='techgrade',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
